#+TITLE: Deal Sourcing and Due Diligence

Success in PE is as much about doing good deals as it is about avoiding bad deals.
Two areas that can differentiate an average fund from a great fund are deal sourcing and due diligence.
Deal sourcing is the process in which PE firms screen investment opportunities
Once an investment has passed through a fund's initial deal sourcing filter, the next step is thorough DD.

This chapter provides an overview of the deal sourcing and DD processes for mature target companies.

* Generating Deal Flow

There are two main ways to source deals: proprietary deal flow sourced through inhouse resources and intermediated deal flow sourced through paid third parties.

** Proprietary Deal Flow

Proprietary deals are sourced directly by a PE firm without the assistance of financial advisors.
These are often more tailored to a fund's size and sector requirements, provide a direct link to a target
company's management team, and have a higher chance for exclusivity than deals sourced through intermediaries.

** Intermediated Deal Flow

Paid intermediaries -- such as integrated investment banks, M&A boutiques, and corporate advisory arms of accounting firms -- play a key role in deal sourcing for larger growth equity and buyout funds. The bulk of these intermediaries compensation comes in the form of a success fee contingent on the completion of a transaction, with a retainer fee occasionally covering costs over the course of the engagement.

** Deal Sourcing Statistics

Younger PE firms managing smaller funds or inveseting in emerging markets tend to source more deals in house, while firms executing large buyouts derive a smaller percentage from their proprietary networks.

VC firms rely far less on paid intermediaries to source deals, drawing more on proprietary deal flow generated by the firm's reputation and the personal networks of its partners.

* Due Diligence Considerations

Once an attractive target company has been identified, DD is the next critical step in the investment process.
Throughout the DD process, PE firms assess the viability of a target's business model relative to their investment thesis.

* Preliminary DD
- NDA (Non-Disclosure Agreement)

A non-disclosure agreement is executed between the PE firm and a target company so that non-public information can be securely exchanged; these agreements cover all information shared during the DD, negotiation, and closing process.
An NDA limits the buyer's ability to freely discuss the target with industry players.
The buyer will typically undertake preliminary DD on its own and sign the NDA only when additional input from the seller is needed.

- CIM (Confidential Information Memorandum)
The first formal document shared by a target. It provides an up-to-date overview of its business and the investment opportunity.

- Management Presentation
Tends to represent the first face-to-face meeting between a PE firm and the company's management in an intermediated DD process.


* Formal DD

The information gained from preliminary DD is organized in a Preliminary Investment Memorandum and is submitted to the PE firm's IC.

- Deal Team

Typically consists of several professionals from the PE firm responsible for driving the investment process and managing a host of external advisors. These advisors typically include consultants, lawyers, and accountants.

- DD Questionaire

Prepared by the deal team and submitted to the target to collect material information related to the invesetment opportunity.

- Data Room

The target and its advisors establish and maintain a data room that contains material documentation for the DD process. Documents shared include historical financial statements and financial projections, shareholding agreements and corporate charters, employment contracts and compensation plans, contracts with key suppliers and customers, and other key company agreements.

- Site Visit

Provides deal teams with the opportunity to gain an understanding of a target's operations in person and typically take place at company offices and facilities.

* Due Diligence Areas

PE firms focus the DD process on specific aspects of a target company: commercial, financial, legal, and human resources.

- Commercial DD (CDD)

The goal of CDD is to better understand the company's business model and explore how the company addresses the needs of its customers, capitalizes on key industry trends, and navigates the competitive environment.

Examples of CDD red flags that may halt an investment include:
  - Shrinking market size and/or declining market share
  - Disruptive and commoditization threats
  - Dependence on powerful suppliers or a concentrated customer base

- Financial DD (FDD)

Includes a detailed examination of a target's historical financial statements and management's financial projections. Typically conducted in conjunction with an accounting firm engaged to thoroughly review audited historical financial statements (generally last 3 to 5 years).

Oftentimes centers on establishing a normalized earnings before interest, tax, depreciation, and amortization (EBITDA) and target working capital, which form a key input for valuation and negotiation at a later stage in the investment process.

Examples of FDD red flags:
  - Off-balance sheet financial instruments
  - Weakening working capital trends
  - Accounting adjustments to obscure actual performance

- Legal DD (LDD)

During LDD, deal teams review a target's material legal documentation and assess the legal status of its key stakeholders.
Law firms are typically engaged to conduct a thorough review of corporate records, material corporate agreements, and intellectual property rights. Environmental, social, and governance issues, the contractual underpinnings of future liabilities -- such as employee pension and benefit programs -- and pending litigation are also examined to determine potential cash flow and reputational impacts on the target.

Examples of LDD red flags:
  - Pending regulatory issues
  - Corruption and bribery accusations
  - Insufficient protection of intellectual property
  - Questionable ownership rights

- Human Resources DD (HRDD)

A thorough review of the capabilities of key employees at a target, starting with the management team.
Beyond senior executives, HRDD extends to line managers and other key employees in the target's talent pool.
Other items assessed include recruitment and retention programs, employment contracts, compensation, and benefit programs.

Examples of HRDD red flags:
  - Frequent board changes
  - The management team deciding to cash out all its equity
  - Strong personal loyalty to existing owners

* Key Learning Points

- Deal sourcing and DD are the first steps of the investment process. A PE fund's IC will rely on the information gathered during the DD process when making an investment decision
- PE firms are keen to develop proprietary deal flow; nevertheless, intermediated deals, referred through investment banks and advisors, make up a significant part of the deals sources -- especially for larger transactions and buyouts
- Once a suitable target company is found and pas passed an initial screening during deal sourcing, the deal team will proceed into the formal phase of the DD process
- PE firms conduct DD across four main areas of the target company: commercial, financial, legal, and human resources

* Chips on the Side (B): The Buyout of Avago Technologies
