#+TITLE: Private Equity Essentials

PE funds invest long-term capital in private (or, at time, public) companies in return for an equity stack that is not freely tradable on a public market. In this book, PE is broadly defined and includes venture capital, growth capital, and buyout funds.

* Private Equity Funds Defined

A PE fund is a stand-alone investment vehicle managed by a PE firm on behalf of a group of investors. The capital is raised with a clear mandate to acquire equity stakes in private companies and divest them over time.

** PE Firm

A company with expertise in executing a venture, growth, or buyout investment strategy. It raises and advises a fund (if successful, a family of funds) generally through two separate but affiliated legal entities: the GP (General Partner) and the Investment Manager.

** Limited Partners

Investors, or Limited Partners, contribute the largest share of capital to any PE fund raised. They participate as passive investors, with an individual LP's liability limited to the capital committed to the fund.

** General Partner

A fund's GP is wholly responsible for all aspects related to managing the fund and has a fiduciary duty to act solely in the interest of the fund's investors. It will issue capital calls to LPs and make all investment and divestment decisions for the fund in line with the mandate set out in its Limited Partnership Agreement (LPA). A GP will also commit capital to the fund to align its interest with that of the fund's LPs by ensuring that the firm's partners have "skin in the game". The GP stake is usually around 1-5%, but rarely exceeds 10% of the fund's total capital raised.

** Investment Manager

In practice the investment manager conducts the day-to-day activities of a PE fund; they evaluate potential investment opportunities, provide advisory servers to the fund's portfolio companies, and manage the fund's audit and reporting processes. The manager is paid a management fee by the fund for these services, some of which may be passed on to a subadvisor. The management fee is typically set at around 1.5 - 2% of committed capital during the investment period of the fund.

** Portfolio Company

Over its lifecycle, a PE fund will invest in a limited number of companies which represent its investment portfolio.

* The GP Perspective

PE funds structured as limited partnerships are typically raised for a 10-year term plus two one-year extensions, commonly referred to as the "10+2" model. Generally, a GP will deploy capital during the first four to five years of a fund's life and harvest capital during its remaining years. The two optional years allow the GP to extend a fund's lifespan at its discretion if and when additional time is needed to prudently exit all investments.

** Fundraising

PE firms raise capital for a fund by securing capital commitments from investors (LPs) through a series of fund closings. The total amount raised by a PE firm in a fundraising period is known as a fund's committed capital.

** Investment Period

Rather than receiving the committed capital on day one, a GP draws down LP commitments over the course of a fund's investment period. The length of the investment period is defined in a fund's governing documents and typically lasts four to five years from the date of its first closing; a GP may at times extend the investment period a year or two, with approval from its LPs.

GPs draw down investor capital by making "capital calls" to fund suitable investment opportunities or to pay fund fees and expenses. LPs must meet capital calls within a short period, typically about 10 business days. If an LP fails to do so, the GP can do things like charge a high interest rate, or sell the defaulting LP's interest on the secondaries market. The portion of LP's committed capital that has been called and invested is referred to as contributed capital. A fund's uninvested committed capital is referred to as its "dry powder". Similarly, the total amount of uninvested committed capital across the industry is referred to as the industry's dry powder.

** Holding Period

Typically range from 3 to 7 years following investment.

** Divestment Period

This is the period in which the GP exits its investments profitably. This is the exit strategy.
This forms an important part of the investment rationale from the start.

* The LP Perspective

** The J-Curve

A PE J-curve represents an LP's cumulative net cash flow position in a single fund over time.

** The Fee Structure and Economics of PE

The fee structure in PE is commonly referred to as "2 and 20" and defines how a fund's investment manager and GP -- and in turn its PE professionals -- are compensated.

- The 2% is the mgmt fee paid by the LPs per annum to a fund's investment manager
- The 20% represents the percentage of net fund profits -- referred to as carried interest, or carry -- paid to its GP
- The majority of profits, 80%, generated by a fund is distributed pro rata to a fund's LPs.

** Management Fees

These fees are generally in the range of 1.3% to 2.5% depending on the size and strategy of the fund and bargaining power of the PE firm during fundraising.

Management fees accrue from a fund's first closing onwards and are usually paid either quarterly or semi-annually in advance. They are charged on committed capital during the investment period and on net invested capital after the investment period.

** Other Fees

The main fee categories are transaction fees linked to a fund's investment in and exit from a portfolio company and monitoring fees for advisory and consulting services provided to portfolio companies during the holding period.

** Carried Interest

Proceeds from a successful exit are distributed to a fund's LPs and its GP in line with a distribution "waterfall" set out in a fund's LPA.

In a typical distribution waterfall, PE funds will return all invested capital and provide a minimum return to investors -- a fund's hurdle rate or preferred return -- before any carried interest is paid out to the GP.
After the hurdle rate has been reached, PE funds will typically include a "catch-up" mechanism that provides distributions to the GP until it has received 20% of all net profits paid out up to this point.

The industry uses 2 standard models to calculate distributions to LPs:

- All Capital First
  - aka European-style Waterfall
  - This entitles a GP to carried interest only after all capital contributed by investors over a fund's life has been returned and any capital required to satisfy a hurdle rate or preferred return has been distributed.

- Deal-by-Deal Carry (with loss carry-forward):
  - aka American-style Waterfall
  - Entitled a GP to carried interest after each profitable exit from a portfolio investment during the fund's life, but only after investors have received their invested capital from the deal in question, a preferred return and a "make whole" payment for any losses incurred on prior deals.

* Key Learning Points

- PE is a simple business -- buy a stake in a company (minority or majority), improve the business and sell it after a limited holding period

- The preferred method employed by PE firms is to raise and invest in individual funds, which they manage on behalf of investors (LPs). PE funds are typically structured asa closed-end limited partnerships that require investors to commit capital for a period of 10 years or more.

- PE funds differ from traditional asset classes due to their illiquidity and the unpredictable cash flows generated from their investments

- Both the fee structure and profit sharing arrangements in PE ensure alignment of interest; incentives change as the funds mature
