#+TITLE: Chapter 19: Performance Reporting
#+AUTHOR: Michael Rose

Performance reporting is the formal process through which general partners (GPs) communicate a fund's activity and interim returns to limited partners (LPs) throughout the holding period.

* Interim Fund Performance

The performance of a PE fund is reported to its LPs on a quarterly basis.

* Company Valuation

The valuation process begins by establishing the realized and/or unrealized value in each portfolio company. Determing an investment's realized value is straightforward, as it equals the proceeds generated from a successful partial or full exit from the fund's position in a company. For unrealized value, the concept of "fair value" has been the market standard since the 2009 financial crisis.

*Fair Value* is defined as the price that a fund would realistically receive for the sale of an asset (or would pay for a liability) in a transaction between market participants on the reporting date. It is set via multiples from recent industry transactions, comparable public companies, and investments in the portfolio company itself.

* Gross Performance

With realized and unrealized valuations of its portfolio companies in hand, a GP will calculate a range of fund-level performance metrics, including the fund's MoM, NAV, and IRR.

MoM (Multiples of Money) is realized + unrealized / capital invested
NAV is the sum of the unrealized equity value in a fund's portfolio companies
IRR is trickier

* Net Performance

To arrive at a fund's net performance, LPs must adjust the reported gross performance -- both in terms of MoM and IRR -- to account for any fees or profit sharing paid to the GP, namely (but not restricted to) annual management fees and carried interest.

* The IRR Conundrum

IRR is the performance metric of choice in the PE industry, and represents the discount rate that renders the net present value of a series of cash flows of an investment zero.

Some problems with IRR:

- There is a built in "reinvestment assumption" that capital distributed to LPs will be reinvested over the fund's term at the same IRR generated at exit. Therefore, a high IRR (>25%) generated by a successful exit early in a PE fund's life is likely to overstate the real economic performance of the fund as the probability of finding a comparably high IRR over the remaining fund term is low. This incentivizes a GP to aggressively exit portfolio companies early in a fund's lifecycle to lock in a high (fund-level) IRR.
- It fails to take into account the LPs' cost of holding capital until it is called for investment
- There is variability in how the metric is applied by GPs
- The IRR is an absolute measure and doesn't calculate performance relative to a benchmark or market return

* Modified IRR

The MIRR overcomes the reinvestment assumption problem of the standard IRR model by assuming that positive cash flows to LPs are reinvesetetd at the cost of capital or a broad public market benchmark. It also accounts for the cost of uncalled capital.

* Key Learning Points

- Given the private nature of PE investments, arriving at a fair valuation of a fund's investments during the holding period can be a complex and controversial exercise.
- The standard performance measures in PE - MoM and IRR - need to be well understood to allow for a meaningful comparison of PE funds
- Comparing the performance of PE portfolios to that of more liquid assets is not trivial; the PME and time-weighted returns are suitable methods for investors

* Case Study #18: Private Equity in Frontier Markets: Creating a Fund in Georgia
